### ISSUE TITLE
AttributeError: 'Version' object has no attribute '_cmp_precedence_key'

### ISSUE THREAD

**Issue by rizzini** [digint/btrbk#488]
I'm getting this error recently. I don't know what on my side could be causing it. 
OS: Arch Linux / [Full specs](https://github.com/rizzini/Dotfiles/tree/master/Documentos/hardware_specs).
```
ERROR (refind_btrfs/__init__.py/main): An unexpected error happened, exiting...
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/refind_btrfs/__init__.py", line 80, in main
    exit_code = runner.run()
File "/usr/lib/python3.10/site-packages/refind_btrfs/service/watchdog_runner.py", line 73, in run
    package_config = package_config_provider.get_config()
File "/usr/lib/python3.10/site-packages/refind_btrfs/utility/file_package_config_provider.py", line 119, >
    persisted_package_config = persistence_provider.get_package_config()
File "/usr/lib/python3.10/site-packages/refind_btrfs/utility/shelve_persistence_provider.py", line 56, in>
    item = self._get_item(db_key, local_db)
File "/usr/lib/python3.10/site-packages/refind_btrfs/utility/shelve_persistence_provider.py", line 136, i>
    return local_db.get(value_key) if actual_version >= current_version else None
File "/usr/lib/python3.10/site-packages/semantic_version/base.py", line 504, in __ge__
    return self._cmp_precedence_key >= other._cmp_precedence_key
AttributeError: 'Version' object has no attribute '_cmp_precedence_key'
```

**Comment by rizzini** [comment]
Ops.. Wrong project.
